runtime: python3
env: flex
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /
  static_files: website/index.html
  upload: website/index.html

- url: /
  static_dir: website

